### ISSUE TITLE
throws error

### ISSUE THREAD

**Issue by jimmywarting** [bmeck/local-fs-https-imports#5]
tried to follow "usage"
this is what i got when running `local-fs-https-imports app.js > policy.json`

```js
node_modules/local-fs-https-imports/bin/local-fs-https-imports.js:14
  throw new Error('must supply policy location');
        ^

Error: must supply policy location
```

it did create a policy.json file doe

i bet it should be `local-fs-https-imports app.js policy.json` cuz that worked out for me

**Comment by bmeck** [comment]
updated readme. thanks
